title: "Security Feeds"
author: "Luca Barba"
email: "alucab@alucab.org"
description: "And I assure you there is a mark on the door."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header


# Your website URL (e.g. http://amitmerchant1990.github.io or http://www.amitmerchant.com)
# Used for Sitemap.xml and your RSS feed
url: https://alucab.github.io/testvulnfeeds
enforce_ssl: https://alucab.github.io/testvulnfeeds

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/testvulnfeeds"

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem


exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME
  - old
